### ISSUE TITLE
new errors 4.0 branch

### ISSUE THREAD

**Issue by blindpet** [comotion/VSF#20]
Should probably create an empty local.vcl

    Cannot read file '/etc/varnish/security/local.vcl': No such file or directory
    ('/etc/varnish/security/vsf.vcl' Line 13 Pos 9)
    include "/etc/varnish/security/local.vcl";
    --------#################################-

Forgot to uncomment this line

    Message from VCC-compiler:
    Syntax error at
    ('/etc/varnish/security/rules/protocol.vcl' Line 33 Pos 5)
    http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.5
    ----#-------------------------------------------------------

Not sure how to fix this besides just commenting it out

    Error:
    Message from VCC-compiler:
    Function sec_throttle redefined
    ('/etc/varnish/security/vsf.vcl' Line 156 Pos 5)
    sub sec_throttle {
    ----############--

**Comment by comotion** [comment]
I made vsf reference local.vcl for you to put your custom/site specific rules into before VSF logic. All you need to do is create the file.

**Comment by blindpet** [comment]
Thanks, it was more for new users and documentation purposes. Just like an empty file with a comment saying put your site specific rules here.

**Comment by comotion** [comment]
I did this but called it `local.vcl.example`

This is tricky as long as the installastion instructions are "clone the repo" because we want people to contribute changes to vsf code, which is best done by keeping their site specific code separate. If I ship the repo with an empty file everyone will end up with diffs to it.

Hopefully not a problem once we make distro-specific packages for VSF. This is a priority for me, above better quality rules even, to make installation a breeze.

**Comment by blindpet** [comment]
Gotcha, with my instructions I find it easy to install and will be posting the full walkthrough guide sometime soon (one for 3.0 and one for 4.x).

**Comment by comotion** [comment]
dunno if you saw it but I updated the README about this
